edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "default"
reorder_imports = true
reorder_modules = true
format_code_in_doc_comments = true
trailing_comma = "Vertical"
